<head>
	<title>Ecstasy Gym</title>
	<!-- start: META -->
	<meta charset="utf-8" />
	<!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<meta content="" name="description" />
	<meta content="" name="author" />
	<!-- end: META -->
	<!-- start: MAIN CSS -->
	<link href='http://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700,200,100,800' rel='stylesheet' type='text/css'>


	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/iCheck/skins/all.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/animate.css/animate.min.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/owl-carousel/owl-carousel/owl.carousel.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/owl-carousel/owl-carousel/owl.theme.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/owl-carousel/owl-carousel/owl.transitions.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/summernote/dist/summernote.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/fullcalendar/fullcalendar/fullcalendar.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/toastr/toastr.min.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap-select/bootstrap-select.min.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap-switch/dist/css/bootstrap3/bootstrap-switch.min.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/DataTables/media/css/DT_bootstrap.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/css/styles.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/css/styles-responsive.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/css/plugins.css">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/css/themes/theme-style8.css" type="text/css" id="skin_color">
    <link rel="stylesheet" href="<?php echo base_url();?>public/assets/css/print.css" type="text/css" media="print" />
    <link href="<?php echo base_url();?>public/assets/plugins/bootstrap-modal/css/bootstrap-modal-bs3patch.css" rel="stylesheet" type="text/css"/>
	<link href="<?php echo base_url();?>public/assets/plugins/bootstrap-modal/css/bootstrap-modal.css" rel="stylesheet" type="text/css"/>
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap-social-buttons/bootstrap-social.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/ladda-bootstrap/dist/ladda.min.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/ladda-bootstrap/dist/ladda-themeless.min.css">
	<link rel="stylesheet" type="text/css" href="<?php echo base_url();?>public/assets/plugins/select2/select2.css" />
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/lightbox2/css/lightbox.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/css/themes/theme-default.css" type="text/css" id="skin_color">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/weather-icons/css/weather-icons.min.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/nvd3/nv.d3.min.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap-datetimepicker/css/datetimepicker.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/x-editable/css/bootstrap-editable.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/typeaheadjs/lib/typeahead.js-bootstrap.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/jquery-address/address.css">
		

	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/wysihtml5/bootstrap-wysihtml5-0.0.2/bootstrap-wysihtml5-0.0.2.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/wysihtml5/bootstrap-wysihtml5-0.0.2/wysiwyg-color.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/jQuery-File-Upload/css/jquery.fileupload-ui.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/Jcrop/css/jquery.Jcrop.min.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/datepicker/css/datepicker.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap-colorpalette/css/bootstrap-colorpalette.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/jQuery-Tags-Input/jquery.tagsinput.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/bootstrap-colorpalette/css/bootstrap-colorpalette.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/dropzone/downloads/css/dropzone.css">
	<link href="<?php echo base_url();?>public/assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.css" rel="stylesheet"/>
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/slider/css/slider.css">
	<link rel="stylesheet" href="<?php echo base_url();?>public/assets/plugins/jQRangeSlider/css/classic-min.css">
	<link href="<?php echo base_url();?>public/assets/plugins/sweetalert/lib/sweet-alert.css" rel="stylesheet" />

	</head>

