<script src="<?php echo base_url();?>public/assets/plugins/jQuery/jquery-2.1.1.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jquery-ui/jquery-ui-1.10.2.custom.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/blockUI/jquery.blockUI.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/iCheck/jquery.icheck.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/moment/min/moment.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/perfect-scrollbar/src/jquery.mousewheel.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/perfect-scrollbar/src/perfect-scrollbar.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/bootbox/bootbox.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jquery.scrollTo/jquery.scrollTo.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/ScrollToFixed/jquery-scrolltofixed-min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jquery.appear/jquery.appear.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jquery-cookie/jquery.cookie.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/velocity/jquery.velocity.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/TouchSwipe/jquery.touchSwipe.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/owl-carousel/owl-carousel/owl.carousel.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jquery-mockjax/jquery.mockjax.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/toastr/toastr.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-modal/js/bootstrap-modal.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-modal/js/bootstrap-modalmanager.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/fullcalendar/fullcalendar/fullcalendar.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-switch/dist/js/bootstrap-switch.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-fileupload/bootstrap-fileupload.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/DataTables/media/js/jquery.dataTables.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/truncate/jquery.truncate.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/summernote/dist/summernote.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-daterangepicker/daterangepicker.js"></script>
<script src="<?php echo base_url();?>public/assets/js/subview.js"></script>
<script src="<?php echo base_url();?>public/assets/js/subview-examples.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-paginator/src/bootstrap-paginator.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jquery.pulsate/jquery.pulsate.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/holder/holder.js"></script>
<script src="<?php echo base_url();?>public/assets/js/ui-elements.js"></script>
<script src="<?php echo base_url();?>public/assets/js/main.js"></script>
<script src="<?php echo base_url();?>public/assets/js/ui-subview.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jQRangeSlider/jQAllRangeSliders-min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/modernizr/modernizr.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/slider/js/bootstrap-slider.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jQuery-Knob/js/jquery.knob.js"></script>
<script src="<?php echo base_url();?>public/assets/js/ui-sliders.js"></script>
<script src="<?php echo base_url();?>public/assets/js/ui-notifications.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/sweetalert/lib/sweet-alert.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/nestable/jquery.nestable.js"></script>
<script src="<?php echo base_url();?>public/assets/js/ui-modals.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/ladda-bootstrap/dist/spin.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/ladda-bootstrap/dist/ladda.min.js"></script>
<script src="<?php echo base_url();?>public/assets/js/ui-buttons.js"></script>
<script src="<?php echo base_url();?>public/assets/js/ui-animations.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>public/assets/plugins/select2/select2.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/tableExport/tableExport.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/tableExport/jquery.base64.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/tableExport/html2canvas.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/tableExport/jspdf/libs/sprintf.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/tableExport/jspdf/jspdf.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/tableExport/jspdf/libs/base64.js"></script>
<script src="<?php echo base_url();?>public/assets/js/table-export.js"></script>
<script type="text/javascript" src="<?php echo base_url();?>public/assets/js/table-data.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jquery.pulsate/jquery.pulsate.min.js"></script>
<script src="<?php echo base_url();?>public/assets/js/pages-user-profile.js"></script>
<script src="<?php echo base_url();?>public/assets/js/pages-timeline.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/mixitup/src/jquery.mixitup.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/lightbox2/js/lightbox.min.js"></script>
<script src="<?php echo base_url();?>public/assets/js/pages-gallery.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
<script src="<?php echo base_url();?>public/assets/js/pages-calendar.js"></script>
<script src="<?php echo base_url();?>public/assets/js/login.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/holder/holder.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jquery.sparkline/jquery.sparkline.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/easy-pie-chart/dist/jquery.easypiechart.min.js"></script>
<script src="<?php echo base_url();?>public/assets/js/index.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/x-editable/js/bootstrap-editable.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/typeaheadjs/typeaheadjs.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/typeaheadjs/lib/typeahead.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jquery-address/address.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/wysihtml5/bootstrap-wysihtml5-0.0.2/wysihtml5-0.3.0.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/wysihtml5/bootstrap-wysihtml5-0.0.2/bootstrap-wysihtml5.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/wysihtml5/wysihtml5.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/x-editable/demo-mock.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/x-editable/demo.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jQuery-Smart-Wizard/js/jquery.smartWizard.js"></script>
<script src="<?php echo base_url();?>public/assets/js/form-wizard.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/ckeditor/ckeditor.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/ckeditor/adapters/jquery.js"></script>
<script src="<?php echo base_url();?>public/assets/js/form-validation.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/Jcrop/js/jquery.Jcrop.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/Jcrop/js/jquery.color.js"></script>
<script src="<?php echo base_url();?>public/assets/js/form-image-cropping.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jquery-inputlimiter/jquery.inputlimiter.1.3.1.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/autosize/jquery.autosize.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/select2/select2.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jquery.maskedinput/src/jquery.maskedinput.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jquery-maskmoney/jquery.maskMoney.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-timepicker/js/bootstrap-timepicker.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-colorpicker/js/commits.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-colorpalette/js/bootstrap-colorpalette.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jQuery-Tags-Input/jquery.tagsinput.js"></script>
<script src="<?php echo base_url();?>public/assets/js/form-elements.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/dropzone/downloads/dropzone.min.js"></script>
<script src="<?php echo base_url();?>public/assets/js/form-dropzone.js"></script>
<script src="<?php echo base_url();?>public/assets/js/charts.js"></script>
<script src="<?php echo base_url();?>public/assets/plugins/jstree/dist/jstree.min.js"></script>
<script src="<?php echo base_url();?>public/assets/js/ui-treeview.js"></script>
<script src="<?php echo base_url();?>public/alerta.js"></script>
<script>
jQuery(document).ready(function() {
Main.init();
SVExamples.init();
Index.init();
TableData.init();
FormWizard.init();
UIModals.init();
FormElements.init();
Animation.init();
Timeline.init();
Calendar.init();

});
</script>